# Generated by Django 4.1.5 on 2023-01-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '주문 댓글', 'verbose_name_plural': '주문 댓글'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='주문'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='shinhan_order_comment',
        ),
    ]
